steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - ujihisa-test
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --max-instances=1
  - --entry-point=index
