version: '3'
services:
  practice-cloud-functions:
    container_name: practice-cloud-functions
    build:
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=8080
    working_dir: /usr/src/app
  firestore-emulator:
    build:
      context: .
      dockerfile: firestore-emulator.Dockerfile
  yaichi:
    image: mtsmfm/yaichi:1.7.0
    ports:
      - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
